#ifndef LIBBISMUTH_OP_H
#define LIBBISMUTH_OP_H

#define OP_BRK_S        0x00
#define OP_ORA_DXI      0x01
#define OP_COP_S        0x02
#define OP_ORA_DS       0x03
#define OP_TBS_D        0x04
#define OP_ORA_D        0x05
#define OP_ASL_D        0x06
#define OP_ORA_DL       0x07
#define OP_PHP_S        0x08
#define OP_ORA_IMM      0x09
#define OP_ASL_AC       0x0a
#define OP_PHD_S        0x0b
#define OP_TSB_A        0x0c
#define OP_ORA_A        0x0d
#define OP_ASL_A        0x0e
#define OP_ORA_AL       0x0f
#define OP_BPL_R        0x10
#define OP_ORA_DYI      0x11
#define OP_ORA_DI       0x12
#define OP_ORA_DYSI     0x13
#define OP_TRB_D        0x14
#define OP_ORA_DX       0x15
#define OP_ASL_DX       0x16
#define OP_ORA_DYL      0x17
#define OP_CLC          0x18
#define OP_ORA_AY       0x19
#define OP_INC_AC       0x1a
#define OP_TCS          0x1b
#define OP_TRB_A        0x1c
#define OP_ORA_AX       0x1d
#define OP_ASL_AX       0x1e
#define OP_ORA_AXL      0x1f
#define OP_JSR_A        0x20
#define OP_AND_DXI      0x21
#define OP_JSL_AL       0x22
#define OP_AND_DS       0x23
#define OP_BIT_D        0x24
#define OP_AND_D        0x25
#define OP_ROL_D        0x26
#define OP_AND_DL       0x27
#define OP_PLP_S        0x28
#define OP_AND_IMM      0x29
#define OP_ROL_AC       0x2a
#define OP_PLD_S        0x2b
#define OP_BIT_A        0x2c
#define OP_AND_A        0x2d
#define OP_ROL_A        0x2e
#define OP_AND_AL       0x2f
#define OP_BMI_R        0x30
#define OP_AND_DYI      0x31
#define OP_AND_DI       0x32
#define OP_AND_DYSI     0x33
#define OP_BIT_DX       0x34
#define OP_AND_DX       0x35
#define OP_ROL_DX       0x36
#define OP_AND_DYL      0x37
#define OP_SEC          0x38
#define OP_AND_AY       0x39
#define OP_DEC_AC       0x3a
#define OP_TSC          0x3b
#define OP_BIT_AX       0x3c
#define OP_AND_AX       0x3d
#define OP_ROL_AX       0x3e
#define OP_AND_AXL      0x3f
#define OP_RTI_S        0x40
#define OP_EOR_DXI      0x41
#define OP_WDM          0x42
#define OP_EOR_DS       0x43
#define OP_MVP          0x44
#define OP_EOR_D        0x45
#define OP_LSR_D        0x46
#define OP_EOR_DL       0x47
#define OP_PHA_S        0x48
#define OP_EOR_IMM      0x49
#define OP_LSR_AC       0x4a
#define OP_PHK_S        0x4b
#define OP_JMP_A        0x4c
#define OP_EOR_A        0x4d
#define OP_LSR_A        0x4e
#define OP_EOR_AL       0x4f
#define OP_BVC_R        0x50
#define OP_EOR_DYI      0x51
#define OP_EOR_DI       0x52
#define OP_EOR_DYSI     0x53
#define OP_MVN          0x54
#define OP_EOR_DX       0x55
#define OP_LSR_DX       0x56
#define OP_EOR_DYL      0x57
#define OP_CLI          0x58
#define OP_EOR_AY       0x59
#define OP_PHY_S        0x5a
#define OP_TCD          0x5b
#define OP_JMP_AL       0x5c
#define OP_EOR_AX       0x5d
#define OP_LSR_AX       0x5e
#define OP_EOR_AXL      0x5f
#define OP_RTS_S        0x60
#define OP_ADC_DXI      0x61
#define OP_PER_S        0x62
#define OP_ADC_DS       0x63
#define OP_STZ_D        0x64
#define OP_ADC_D        0x65
#define OP_ROR_D        0x66
#define OP_ADC_DL       0x67
#define OP_PLA_S        0x68
#define OP_ADC_IMM      0x69
#define OP_ROR_AC       0x6a
#define OP_RTL_S        0x6b
#define OP_JMP_AI       0x6c
#define OP_ADC_A        0x6d
#define OP_ROR_A        0x6e
#define OP_ADC_AL       0x6f
#define OP_BVS_R        0x70
#define OP_ADC_DYI      0x71
#define OP_ADC_DI       0x72
#define OP_ADC_DYSI     0x73
#define OP_STZ_DX       0x74
#define OP_ADC_DX       0x75
#define OP_ROR_DX       0x76
#define OP_ADC_DYL      0x77
#define OP_SEI          0x78
#define OP_ADC_AY       0x79
#define OP_PLY_S        0x7a
#define OP_TDC          0x7b
#define OP_JMP_AXI      0x7c
#define OP_ADC_AX       0x7d
#define OP_ROR_AX       0x7e
#define OP_ADC_AXL      0x7f
#define OP_BRA_R        0x80
#define OP_STA_DXI      0x81
#define OP_BRL_RL       0x82
#define OP_STA_DS       0x83
#define OP_STY_D        0x84
#define OP_STA_D        0x85
#define OP_STX_D        0x86
#define OP_STA_DL       0x87
#define OP_DEY          0x88
#define OP_BIT_IMM      0x89
#define OP_TXA          0x8a
#define OP_PHB_S        0x8b
#define OP_STY_A        0x8c
#define OP_STA_A        0x8d
#define OP_STX_A        0x8e
#define OP_STA_AL       0x8f
#define OP_BCC_R        0x90
#define OP_STA_DYI      0x91
#define OP_STA_DI       0x92
#define OP_STA_DYSI     0x93
#define OP_STY_DX       0x94
#define OP_STA_DX       0x95
#define OP_STX_DY       0x96
#define OP_STA_DYL      0x97
#define OP_TYA          0x98
#define OP_STA_AY       0x99
#define OP_TXS          0x9a
#define OP_TXY          0x9b
#define OP_STZ_A        0x9c
#define OP_STA_AX       0x9d
#define OP_STZ_AX       0x9e
#define OP_STA_AXL      0x9f
#define OP_LDY_MM       0xa0
#define OP_LDA_DXI      0xa1
#define OP_LDX_IMM      0xa2
#define OP_LDA_DS       0xa3
#define OP_LDY_D        0xa4
#define OP_LDA_D        0xa5
#define OP_LDX_D        0xa6
#define OP_LDA_DL       0xa7
#define OP_TAY          0xa8
#define OP_LDA_IMM      0xa9
#define OP_TAX          0xaa
#define OP_PLB_S        0xab
#define OP_LDY_A        0xac
#define OP_LDA_A        0xad
#define OP_LDX_A        0xae
#define OP_LDA_AL       0xaf
#define OP_BCS_R        0xb0
#define OP_LDA_DYI      0xb1
#define OP_LDA_DI       0xb2
#define OP_LDA_DYSI     0xb3
#define OP_LDY_DX       0xb4
#define OP_LDA_DX       0xb5
#define OP_LDX_DY       0xb6
#define OP_LDA_DYL      0xb7
#define OP_CLV          0xb8
#define OP_LDA_AY       0xb9
#define OP_TSX          0xba
#define OP_TYX          0xbb
#define OP_LDY_AX       0xbc
#define OP_LDA_AX       0xbd
#define OP_LDX_AY       0xbe
#define OP_LDA_AXL      0xbf
#define OP_CPY_IMM      0xc0
#define OP_CMP_DXI      0xc1
#define OP_REP_IMM      0xc2
#define OP_CMP_DS       0xc3
#define OP_CPY_D        0xc4
#define OP_CMP_D        0xc5
#define OP_DEC_D        0xc6
#define OP_CMP_DL       0xc7
#define OP_INY          0xc8
#define OP_CMP_IMM      0xc9
#define OP_DEX          0xca
#define OP_WAI          0xcb
#define OP_CPY_A        0xcc
#define OP_CMP_A        0xcd
#define OP_DEC_A        0xce
#define OP_CMP_AL       0xcf
#define OP_BNE_R        0xd0
#define OP_CMP_DYI      0xd1
#define OP_CMP_DI       0xd2
#define OP_CMP_DYSI     0xd3
#define OP_PEI_S        0xd4
#define OP_CMP_DX       0xd5
#define OP_DEC_DX       0xd6
#define OP_CMP_DYL      0xd7
#define OP_CLD          0xd8
#define OP_CMP_AY       0xd9
#define OP_PHX_S        0xda
#define OP_STP          0xdb
#define OP_JML_AI       0xdc
#define OP_CMP_AX       0xdd
#define OP_DEC_AX       0xde
#define OP_CML_AXL      0xdf
#define OP_CPX_IMM      0xe0
#define OP_SBC_DXI      0xe1
#define OP_SEP_IMM      0xe2
#define OP_SBC_DS       0xe3
#define OP_CPX_D        0xe4
#define OP_SBC_D        0xe5
#define OP_INC_D        0xe6
#define OP_SBC_DL       0xe7
#define OP_INX          0xe8
#define OP_SBC_IMM      0xe9
#define OP_NOP          0xea
#define OP_XBA          0xeb
#define OP_CPX_A        0xec
#define OP_SBC_A        0xed
#define OP_INC_A        0xee
#define OP_SBC_AL       0xef
#define OP_BEQ_R        0xf0
#define OP_SBC_DYI      0xf1
#define OP_SBC_DI       0xf2
#define OP_SBC_DYSI     0xf3
#define OP_PEA_S        0xf4
#define OP_SBC_DX       0xf5
#define OP_INC_DX       0xf6
#define OP_SBC_DYL      0xf7
#define OP_SED          0xf8
#define OP_SBC_AY       0xf9
#define OP_PLX_S        0xfa
#define OP_XCE          0xfb
#define OP_JSR_AXI      0xfc
#define OP_SBC_AX       0xfd
#define OP_INC_AX       0xfe
#define OP_SBC_AXL      0xff

#define OP_BRK_S_X        0x100
#define OP_ORA_DXI_X      0x101
#define OP_COP_S_X        0x102
#define OP_ORA_DS_X       0x103
#define OP_TBS_D_X        0x104
#define OP_ORA_D_X        0x105
#define OP_ASL_D_X        0x106
#define OP_ORA_DL_X       0x107
#define OP_PHP_S_X        0x108
#define OP_ORA_IMM_X      0x109
#define OP_ASL_AC_X       0x10a
#define OP_PHD_S_X        0x10b
#define OP_TSB_A_X        0x10c
#define OP_ORA_A_X        0x10d
#define OP_ASL_A_X        0x10e
#define OP_ORA_AL_X       0x10f
#define OP_BPL_R_X        0x110
#define OP_ORA_DYI_X      0x111
#define OP_ORA_DI_X       0x112
#define OP_ORA_DYSI_X     0x113
#define OP_TRB_D_X        0x114
#define OP_ORA_DX_X       0x115
#define OP_ASL_DX_X       0x116
#define OP_ORA_DYL_X      0x117
#define OP_CLC_X          0x118
#define OP_ORA_AY_X       0x119
#define OP_INC_AC_X       0x11a
#define OP_TCS_X          0x11b
#define OP_TRB_A_X        0x11c
#define OP_ORA_AX_X       0x11d
#define OP_ASL_AX_X       0x11e
#define OP_ORA_AXL_X      0x11f
#define OP_JSR_A_X        0x120
#define OP_AND_DXI_X      0x121
#define OP_JSL_AL_X       0x122
#define OP_AND_DS_X       0x123
#define OP_BIT_D_X        0x124
#define OP_AND_D_X        0x125
#define OP_ROL_D_X        0x126
#define OP_AND_DL_X       0x127
#define OP_PLP_S_X        0x128
#define OP_AND_IMM_X      0x129
#define OP_ROL_AC_X       0x12a
#define OP_PLD_S_X        0x12b
#define OP_BIT_A_X        0x12c
#define OP_AND_A_X        0x12d
#define OP_ROL_A_X        0x12e
#define OP_AND_AL_X       0x12f
#define OP_BMI_R_X        0x130
#define OP_AND_DYI_X      0x131
#define OP_AND_DI_X       0x132
#define OP_AND_DYSI_X     0x133
#define OP_BIT_DX_X       0x134
#define OP_AND_DX_X       0x135
#define OP_ROL_DX_X       0x136
#define OP_AND_DYL_X      0x137
#define OP_SEC_X          0x138
#define OP_AND_AY_X       0x139
#define OP_DEC_AC_X       0x13a
#define OP_TSC_X          0x13b
#define OP_BIT_AX_X       0x13c
#define OP_AND_AX_X       0x13d
#define OP_ROL_AX_X       0x13e
#define OP_AND_AXL_X      0x13f
#define OP_RTI_S_X        0x140
#define OP_EOR_DXI_X      0x141
#define OP_WDM_X          0x142
#define OP_EOR_DS_X       0x143
#define OP_MVP_X          0x144
#define OP_EOR_D_X        0x145
#define OP_LSR_D_X        0x146
#define OP_EOR_DL_X       0x147
#define OP_PHA_S_X        0x148
#define OP_EOR_IMM_X      0x149
#define OP_LSR_AC_X       0x14a
#define OP_PHK_S_X        0x14b
#define OP_JMP_A_X        0x14c
#define OP_EOR_A_X        0x14d
#define OP_LSR_A_X        0x14e
#define OP_EOR_AL_X       0x14f
#define OP_BVC_R_X        0x150
#define OP_EOR_DYI_X      0x151
#define OP_EOR_DI_X       0x152
#define OP_EOR_DYSI_X     0x153
#define OP_MVN_X          0x154
#define OP_EOR_DX_X       0x155
#define OP_LSR_DX_X       0x156
#define OP_EOR_DYL_X      0x157
#define OP_CLI_X          0x158
#define OP_EOR_AY_X       0x159
#define OP_PHY_S_X        0x15a
#define OP_TCD_X          0x15b
#define OP_JMP_AL_X       0x15c
#define OP_EOR_AX_X       0x15d
#define OP_LSR_AX_X       0x15e
#define OP_EOR_AXL_X      0x15f
#define OP_RTS_S_X        0x160
#define OP_ADC_DXI_X      0x161
#define OP_PER_S_X        0x162
#define OP_ADC_DS_X       0x163
#define OP_STZ_D_X        0x164
#define OP_ADC_D_X        0x165
#define OP_ROR_D_X        0x166
#define OP_ADC_DL_X       0x167
#define OP_PLA_S_X        0x168
#define OP_ADC_IMM_X      0x169
#define OP_ROR_AC_X       0x16a
#define OP_RTL_S_X        0x16b
#define OP_JMP_AI_X       0x16c
#define OP_ADC_A_X        0x16d
#define OP_ROR_A_X        0x16e
#define OP_ADC_AL_X       0x16f
#define OP_BVS_R_X        0x170
#define OP_ADC_DYI_X      0x171
#define OP_ADC_DI_X       0x172
#define OP_ADC_DYSI_X     0x173
#define OP_STZ_DX_X       0x174
#define OP_ADC_DX_X       0x175
#define OP_ROR_DX_X       0x176
#define OP_ADC_DYL_X      0x177
#define OP_SEI_X          0x178
#define OP_ADC_AY_X       0x179
#define OP_PLY_S_X        0x17a
#define OP_TDC_X          0x17b
#define OP_JMP_AXI_X      0x17c
#define OP_ADC_AX_X       0x17d
#define OP_ROR_AX_X       0x17e
#define OP_ADC_AXL_X      0x17f
#define OP_BRA_R_X        0x180
#define OP_STA_DXI_X      0x181
#define OP_BRL_RL_X       0x182
#define OP_STA_DS_X       0x183
#define OP_STY_D_X        0x184
#define OP_STA_D_X        0x185
#define OP_STX_D_X        0x186
#define OP_STA_DL_X       0x187
#define OP_DEY_X          0x188
#define OP_BIT_IMM_X      0x189
#define OP_TXA_X          0x18a
#define OP_PHB_S_X        0x18b
#define OP_STY_A_X        0x18c
#define OP_STA_A_X        0x18d
#define OP_STX_A_X        0x18e
#define OP_STA_AL_X       0x18f
#define OP_BCC_R_X        0x190
#define OP_STA_DYI_X      0x191
#define OP_STA_DI_X       0x192
#define OP_STA_DYSI_X     0x193
#define OP_STY_DX_X       0x194
#define OP_STA_DX_X       0x195
#define OP_STX_DY_X       0x196
#define OP_STA_DYL_X      0x197
#define OP_TYA_X          0x198
#define OP_STA_AY_X       0x199
#define OP_TXS_X          0x19a
#define OP_TXY_X          0x19b
#define OP_STZ_A_X        0x19c
#define OP_STA_AX_X       0x19d
#define OP_STZ_AX_X       0x19e
#define OP_STA_AXL_X      0x19f
#define OP_LDY_MM_X       0x1a0
#define OP_LDA_DXI_X      0x1a1
#define OP_LDX_IMM_X      0x1a2
#define OP_LDA_DS_X       0x1a3
#define OP_LDY_D_X        0x1a4
#define OP_LDA_D_X        0x1a5
#define OP_LDX_D_X        0x1a6
#define OP_LDA_DL_X       0x1a7
#define OP_TAY_X          0x1a8
#define OP_LDA_IMM_X      0x1a9
#define OP_TAX_X          0x1aa
#define OP_PLB_S_X        0x1ab
#define OP_LDY_A_X        0x1ac
#define OP_LDA_A_X        0x1ad
#define OP_LDX_A_X        0x1ae
#define OP_LDA_AL_X       0x1af
#define OP_BCS_R_X        0x1b0
#define OP_LDA_DYI_X      0x1b1
#define OP_LDA_DI_X       0x1b2
#define OP_LDA_DYSI_X     0x1b3
#define OP_LDY_DX_X       0x1b4
#define OP_LDA_DX_X       0x1b5
#define OP_LDX_DY_X       0x1b6
#define OP_LDA_DYL_X      0x1b7
#define OP_CLV_X          0x1b8
#define OP_LDA_AY_X       0x1b9
#define OP_TSX_X          0x1ba
#define OP_TYX_X          0x1bb
#define OP_LDY_AX_X       0x1bc
#define OP_LDA_AX_X       0x1bd
#define OP_LDX_AY_X       0x1be
#define OP_LDA_AXL_X      0x1bf
#define OP_CPY_IMM_X      0x1c0
#define OP_CMP_DXI_X      0x1c1
#define OP_REP_IMM_X      0x1c2
#define OP_CMP_DS_X       0x1c3
#define OP_CPY_D_X        0x1c4
#define OP_CMP_D_X        0x1c5
#define OP_DEC_D_X        0x1c6
#define OP_CMP_DL_X       0x1c7
#define OP_INY_X          0x1c8
#define OP_CMP_IMM_X      0x1c9
#define OP_DEX_X          0x1ca
#define OP_WAI_X          0x1cb
#define OP_CPY_A_X        0x1cc
#define OP_CMP_A_X        0x1cd
#define OP_DEC_A_X        0x1ce
#define OP_CMP_AL_X       0x1cf
#define OP_BNE_R_X        0x1d0
#define OP_CMP_DYI_X      0x1d1
#define OP_CMP_DI_X       0x1d2
#define OP_CMP_DYSI_X     0x1d3
#define OP_PEI_S_X        0x1d4
#define OP_CMP_DX_X       0x1d5
#define OP_DEC_DX_X       0x1d6
#define OP_CMP_DYL_X      0x1d7
#define OP_CLD_X          0x1d8
#define OP_CMP_AY_X       0x1d9
#define OP_PHX_S_X        0x1da
#define OP_STP_X          0x1db
#define OP_JML_AI_X       0x1dc
#define OP_CMP_AX_X       0x1dd
#define OP_DEC_AX_X       0x1de
#define OP_CML_AXL_X      0x1df
#define OP_CPX_IMM_X      0x1e0
#define OP_SBC_DXI_X      0x1e1
#define OP_SEP_IMM_X      0x1e2
#define OP_SBC_DS_X       0x1e3
#define OP_CPX_D_X        0x1e4
#define OP_SBC_D_X        0x1e5
#define OP_INC_D_X        0x1e6
#define OP_SBC_DL_X       0x1e7
#define OP_INX_X          0x1e8
#define OP_SBC_IMM_X      0x1e9
#define OP_NOP_X          0x1ea
#define OP_XBA_X          0x1eb
#define OP_CPX_A_X        0x1ec
#define OP_SBC_A_X        0x1ed
#define OP_INC_A_X        0x1ee
#define OP_SBC_AL_X       0x1ef
#define OP_BEQ_R_X        0x1f0
#define OP_SBC_DYI_X      0x1f1
#define OP_SBC_DI_X       0x1f2
#define OP_SBC_DYSI_X     0x1f3
#define OP_PEA_S_X        0x1f4
#define OP_SBC_DX_X       0x1f5
#define OP_INC_DX_X       0x1f6
#define OP_SBC_DYL_X      0x1f7
#define OP_SED_X          0x1f8
#define OP_SBC_AY_X       0x1f9
#define OP_PLX_S_X        0x1fa
#define OP_XCE_X          0x1fb
#define OP_JSR_AXI_X      0x1fc
#define OP_SBC_AX_X       0x1fd
#define OP_INC_AX_X       0x1fe
#define OP_SBC_AXL_X      0x1ff

#define OP_BRK_S_M        0x200
#define OP_ORA_DXI_M      0x201
#define OP_COP_S_M        0x202
#define OP_ORA_DS_M       0x203
#define OP_TBS_D_M        0x204
#define OP_ORA_D_M        0x205
#define OP_ASL_D_M        0x206
#define OP_ORA_DL_M       0x207
#define OP_PHP_S_M        0x208
#define OP_ORA_IMM_M      0x209
#define OP_ASL_AC_M       0x20a
#define OP_PHD_S_M        0x20b
#define OP_TSB_A_M        0x20c
#define OP_ORA_A_M        0x20d
#define OP_ASL_A_M        0x20e
#define OP_ORA_AL_M       0x20f
#define OP_BPL_R_M        0x210
#define OP_ORA_DYI_M      0x211
#define OP_ORA_DI_M       0x212
#define OP_ORA_DYSI_M     0x213
#define OP_TRB_D_M        0x214
#define OP_ORA_DX_M       0x215
#define OP_ASL_DX_M       0x216
#define OP_ORA_DYL_M      0x217
#define OP_CLC_M          0x218
#define OP_ORA_AY_M       0x219
#define OP_INC_AC_M       0x21a
#define OP_TCS_M          0x21b
#define OP_TRB_A_M        0x21c
#define OP_ORA_AX_M       0x21d
#define OP_ASL_AX_M       0x21e
#define OP_ORA_AXL_M      0x21f
#define OP_JSR_A_M        0x220
#define OP_AND_DXI_M      0x221
#define OP_JSL_AL_M       0x222
#define OP_AND_DS_M       0x223
#define OP_BIT_D_M        0x224
#define OP_AND_D_M        0x225
#define OP_ROL_D_M        0x226
#define OP_AND_DL_M       0x227
#define OP_PLP_S_M        0x228
#define OP_AND_IMM_M      0x229
#define OP_ROL_AC_M       0x22a
#define OP_PLD_S_M        0x22b
#define OP_BIT_A_M        0x22c
#define OP_AND_A_M        0x22d
#define OP_ROL_A_M        0x22e
#define OP_AND_AL_M       0x22f
#define OP_BMI_R_M        0x230
#define OP_AND_DYI_M      0x231
#define OP_AND_DI_M       0x232
#define OP_AND_DYSI_M     0x233
#define OP_BIT_DX_M       0x234
#define OP_AND_DX_M       0x235
#define OP_ROL_DX_M       0x236
#define OP_AND_DYL_M      0x237
#define OP_SEC_M          0x238
#define OP_AND_AY_M       0x239
#define OP_DEC_AC_M       0x23a
#define OP_TSC_M          0x23b
#define OP_BIT_AX_M       0x23c
#define OP_AND_AX_M       0x23d
#define OP_ROL_AX_M       0x23e
#define OP_AND_AXL_M      0x23f
#define OP_RTI_S_M        0x240
#define OP_EOR_DXI_M      0x241
#define OP_WDM_M          0x242
#define OP_EOR_DS_M       0x243
#define OP_MVP_M          0x244
#define OP_EOR_D_M        0x245
#define OP_LSR_D_M        0x246
#define OP_EOR_DL_M       0x247
#define OP_PHA_S_M        0x248
#define OP_EOR_IMM_M      0x249
#define OP_LSR_AC_M       0x24a
#define OP_PHK_S_M        0x24b
#define OP_JMP_A_M        0x24c
#define OP_EOR_A_M        0x24d
#define OP_LSR_A_M        0x24e
#define OP_EOR_AL_M       0x24f
#define OP_BVC_R_M        0x250
#define OP_EOR_DYI_M      0x251
#define OP_EOR_DI_M       0x252
#define OP_EOR_DYSI_M     0x253
#define OP_MVN_M          0x254
#define OP_EOR_DX_M       0x255
#define OP_LSR_DX_M       0x256
#define OP_EOR_DYL_M      0x257
#define OP_CLI_M          0x258
#define OP_EOR_AY_M       0x259
#define OP_PHY_S_M        0x25a
#define OP_TCD_M          0x25b
#define OP_JMP_AL_M       0x25c
#define OP_EOR_AX_M       0x25d
#define OP_LSR_AX_M       0x25e
#define OP_EOR_AXL_M      0x25f
#define OP_RTS_S_M        0x260
#define OP_ADC_DXI_M      0x261
#define OP_PER_S_M        0x262
#define OP_ADC_DS_M       0x263
#define OP_STZ_D_M        0x264
#define OP_ADC_D_M        0x265
#define OP_ROR_D_M        0x266
#define OP_ADC_DL_M       0x267
#define OP_PLA_S_M        0x268
#define OP_ADC_IMM_M      0x269
#define OP_ROR_AC_M       0x26a
#define OP_RTL_S_M        0x26b
#define OP_JMP_AI_M       0x26c
#define OP_ADC_A_M        0x26d
#define OP_ROR_A_M        0x26e
#define OP_ADC_AL_M       0x26f
#define OP_BVS_R_M        0x270
#define OP_ADC_DYI_M      0x271
#define OP_ADC_DI_M       0x272
#define OP_ADC_DYSI_M     0x273
#define OP_STZ_DX_M       0x274
#define OP_ADC_DX_M       0x275
#define OP_ROR_DX_M       0x276
#define OP_ADC_DYL_M      0x277
#define OP_SEI_M          0x278
#define OP_ADC_AY_M       0x279
#define OP_PLY_S_M        0x27a
#define OP_TDC_M          0x27b
#define OP_JMP_AXI_M      0x27c
#define OP_ADC_AX_M       0x27d
#define OP_ROR_AX_M       0x27e
#define OP_ADC_AXL_M      0x27f
#define OP_BRA_R_M        0x280
#define OP_STA_DXI_M      0x281
#define OP_BRL_RL_M       0x282
#define OP_STA_DS_M       0x283
#define OP_STY_D_M        0x284
#define OP_STA_D_M        0x285
#define OP_STX_D_M        0x286
#define OP_STA_DL_M       0x287
#define OP_DEY_M          0x288
#define OP_BIT_IMM_M      0x289
#define OP_TXA_M          0x28a
#define OP_PHB_S_M        0x28b
#define OP_STY_A_M        0x28c
#define OP_STA_A_M        0x28d
#define OP_STX_A_M        0x28e
#define OP_STA_AL_M       0x28f
#define OP_BCC_R_M        0x290
#define OP_STA_DYI_M      0x291
#define OP_STA_DI_M       0x292
#define OP_STA_DYSI_M     0x293
#define OP_STY_DX_M       0x294
#define OP_STA_DX_M       0x295
#define OP_STX_DY_M       0x296
#define OP_STA_DYL_M      0x297
#define OP_TYA_M          0x298
#define OP_STA_AY_M       0x299
#define OP_TXS_M          0x29a
#define OP_TXY_M          0x29b
#define OP_STZ_A_M        0x29c
#define OP_STA_AX_M       0x29d
#define OP_STZ_AX_M       0x29e
#define OP_STA_AXL_M      0x29f
#define OP_LDY_MM_M       0x2a0
#define OP_LDA_DXI_M      0x2a1
#define OP_LDX_IMM_M      0x2a2
#define OP_LDA_DS_M       0x2a3
#define OP_LDY_D_M        0x2a4
#define OP_LDA_D_M        0x2a5
#define OP_LDX_D_M        0x2a6
#define OP_LDA_DL_M       0x2a7
#define OP_TAY_M          0x2a8
#define OP_LDA_IMM_M      0x2a9
#define OP_TAX_M          0x2aa
#define OP_PLB_S_M        0x2ab
#define OP_LDY_A_M        0x2ac
#define OP_LDA_A_M        0x2ad
#define OP_LDX_A_M        0x2ae
#define OP_LDA_AL_M       0x2af
#define OP_BCS_R_M        0x2b0
#define OP_LDA_DYI_M      0x2b1
#define OP_LDA_DI_M       0x2b2
#define OP_LDA_DYSI_M     0x2b3
#define OP_LDY_DX_M       0x2b4
#define OP_LDA_DX_M       0x2b5
#define OP_LDX_DY_M       0x2b6
#define OP_LDA_DYL_M      0x2b7
#define OP_CLV_M          0x2b8
#define OP_LDA_AY_M       0x2b9
#define OP_TSX_M          0x2ba
#define OP_TYX_M          0x2bb
#define OP_LDY_AX_M       0x2bc
#define OP_LDA_AX_M       0x2bd
#define OP_LDX_AY_M       0x2be
#define OP_LDA_AXL_M      0x2bf
#define OP_CPY_IMM_M      0x2c0
#define OP_CMP_DXI_M      0x2c1
#define OP_REP_IMM_M      0x2c2
#define OP_CMP_DS_M       0x2c3
#define OP_CPY_D_M        0x2c4
#define OP_CMP_D_M        0x2c5
#define OP_DEC_D_M        0x2c6
#define OP_CMP_DL_M       0x2c7
#define OP_INY_M          0x2c8
#define OP_CMP_IMM_M      0x2c9
#define OP_DEX_M          0x2ca
#define OP_WAI_M          0x2cb
#define OP_CPY_A_M        0x2cc
#define OP_CMP_A_M        0x2cd
#define OP_DEC_A_M        0x2ce
#define OP_CMP_AL_M       0x2cf
#define OP_BNE_R_M        0x2d0
#define OP_CMP_DYI_M      0x2d1
#define OP_CMP_DI_M       0x2d2
#define OP_CMP_DYSI_M     0x2d3
#define OP_PEI_S_M        0x2d4
#define OP_CMP_DX_M       0x2d5
#define OP_DEC_DX_M       0x2d6
#define OP_CMP_DYL_M      0x2d7
#define OP_CLD_M          0x2d8
#define OP_CMP_AY_M       0x2d9
#define OP_PHX_S_M        0x2da
#define OP_STP_M          0x2db
#define OP_JML_AI_M       0x2dc
#define OP_CMP_AX_M       0x2dd
#define OP_DEC_AX_M       0x2de
#define OP_CML_AXL_M      0x2df
#define OP_CPX_IMM_M      0x2e0
#define OP_SBC_DXI_M      0x2e1
#define OP_SEP_IMM_M      0x2e2
#define OP_SBC_DS_M       0x2e3
#define OP_CPX_D_M        0x2e4
#define OP_SBC_D_M        0x2e5
#define OP_INC_D_M        0x2e6
#define OP_SBC_DL_M       0x2e7
#define OP_INX_M          0x2e8
#define OP_SBC_IMM_M      0x2e9
#define OP_NOP_M          0x2ea
#define OP_XBA_M          0x2eb
#define OP_CPX_A_M        0x2ec
#define OP_SBC_A_M        0x2ed
#define OP_INC_A_M        0x2ee
#define OP_SBC_AL_M       0x2ef
#define OP_BEQ_R_M        0x2f0
#define OP_SBC_DYI_M      0x2f1
#define OP_SBC_DI_M       0x2f2
#define OP_SBC_DYSI_M     0x2f3
#define OP_PEA_S_M        0x2f4
#define OP_SBC_DX_M       0x2f5
#define OP_INC_DX_M       0x2f6
#define OP_SBC_DYL_M      0x2f7
#define OP_SED_M          0x2f8
#define OP_SBC_AY_M       0x2f9
#define OP_PLX_S_M        0x2fa
#define OP_XCE_M          0x2fb
#define OP_JSR_AXI_M      0x2fc
#define OP_SBC_AX_M       0x2fd
#define OP_INC_AX_M       0x2fe
#define OP_SBC_AXL_M      0x2ff

#define OP_BRK_S_MX        0x300
#define OP_ORA_DXI_MX      0x301
#define OP_COP_S_MX        0x302
#define OP_ORA_DS_MX       0x303
#define OP_TBS_D_MX        0x304
#define OP_ORA_D_MX        0x305
#define OP_ASL_D_MX        0x306
#define OP_ORA_DL_MX       0x307
#define OP_PHP_S_MX        0x308
#define OP_ORA_IMM_MX      0x309
#define OP_ASL_AC_MX       0x30a
#define OP_PHD_S_MX        0x30b
#define OP_TSB_A_MX        0x30c
#define OP_ORA_A_MX        0x30d
#define OP_ASL_A_MX        0x30e
#define OP_ORA_AL_MX       0x30f
#define OP_BPL_R_MX        0x310
#define OP_ORA_DYI_MX      0x311
#define OP_ORA_DI_MX       0x312
#define OP_ORA_DYSI_MX     0x313
#define OP_TRB_D_MX        0x314
#define OP_ORA_DX_MX       0x315
#define OP_ASL_DX_MX       0x316
#define OP_ORA_DYL_MX      0x317
#define OP_CLC_MX          0x318
#define OP_ORA_AY_MX       0x319
#define OP_INC_AC_MX       0x31a
#define OP_TCS_MX          0x31b
#define OP_TRB_A_MX        0x31c
#define OP_ORA_AX_MX       0x31d
#define OP_ASL_AX_MX       0x31e
#define OP_ORA_AXL_MX      0x31f
#define OP_JSR_A_MX        0x320
#define OP_AND_DXI_MX      0x321
#define OP_JSL_AL_MX       0x322
#define OP_AND_DS_MX       0x323
#define OP_BIT_D_MX        0x324
#define OP_AND_D_MX        0x325
#define OP_ROL_D_MX        0x326
#define OP_AND_DL_MX       0x327
#define OP_PLP_S_MX        0x328
#define OP_AND_IMM_MX      0x329
#define OP_ROL_AC_MX       0x32a
#define OP_PLD_S_MX        0x32b
#define OP_BIT_A_MX        0x32c
#define OP_AND_A_MX        0x32d
#define OP_ROL_A_MX        0x32e
#define OP_AND_AL_MX       0x32f
#define OP_BMI_R_MX        0x330
#define OP_AND_DYI_MX      0x331
#define OP_AND_DI_MX       0x332
#define OP_AND_DYSI_MX     0x333
#define OP_BIT_DX_MX       0x334
#define OP_AND_DX_MX       0x335
#define OP_ROL_DX_MX       0x336
#define OP_AND_DYL_MX      0x337
#define OP_SEC_MX          0x338
#define OP_AND_AY_MX       0x339
#define OP_DEC_AC_MX       0x33a
#define OP_TSC_MX          0x33b
#define OP_BIT_AX_MX       0x33c
#define OP_AND_AX_MX       0x33d
#define OP_ROL_AX_MX       0x33e
#define OP_AND_AXL_MX      0x33f
#define OP_RTI_S_MX        0x340
#define OP_EOR_DXI_MX      0x341
#define OP_WDM_MX          0x342
#define OP_EOR_DS_MX       0x343
#define OP_MVP_MX          0x344
#define OP_EOR_D_MX        0x345
#define OP_LSR_D_MX        0x346
#define OP_EOR_DL_MX       0x347
#define OP_PHA_S_MX        0x348
#define OP_EOR_IMM_MX      0x349
#define OP_LSR_AC_MX       0x34a
#define OP_PHK_S_MX        0x34b
#define OP_JMP_A_MX        0x34c
#define OP_EOR_A_MX        0x34d
#define OP_LSR_A_MX        0x34e
#define OP_EOR_AL_MX       0x34f
#define OP_BVC_R_MX        0x350
#define OP_EOR_DYI_MX      0x351
#define OP_EOR_DI_MX       0x352
#define OP_EOR_DYSI_MX     0x353
#define OP_MVN_MX          0x354
#define OP_EOR_DX_MX       0x355
#define OP_LSR_DX_MX       0x356
#define OP_EOR_DYL_MX      0x357
#define OP_CLI_MX          0x358
#define OP_EOR_AY_MX       0x359
#define OP_PHY_S_MX        0x35a
#define OP_TCD_MX          0x35b
#define OP_JMP_AL_MX       0x35c
#define OP_EOR_AX_MX       0x35d
#define OP_LSR_AX_MX       0x35e
#define OP_EOR_AXL_MX      0x35f
#define OP_RTS_S_MX        0x360
#define OP_ADC_DXI_MX      0x361
#define OP_PER_S_MX        0x362
#define OP_ADC_DS_MX       0x363
#define OP_STZ_D_MX        0x364
#define OP_ADC_D_MX        0x365
#define OP_ROR_D_MX        0x366
#define OP_ADC_DL_MX       0x367
#define OP_PLA_S_MX        0x368
#define OP_ADC_IMM_MX      0x369
#define OP_ROR_AC_MX       0x36a
#define OP_RTL_S_MX        0x36b
#define OP_JMP_AI_MX       0x36c
#define OP_ADC_A_MX        0x36d
#define OP_ROR_A_MX        0x36e
#define OP_ADC_AL_MX       0x36f
#define OP_BVS_R_MX        0x370
#define OP_ADC_DYI_MX      0x371
#define OP_ADC_DI_MX       0x372
#define OP_ADC_DYSI_MX     0x373
#define OP_STZ_DX_MX       0x374
#define OP_ADC_DX_MX       0x375
#define OP_ROR_DX_MX       0x376
#define OP_ADC_DYL_MX      0x377
#define OP_SEI_MX          0x378
#define OP_ADC_AY_MX       0x379
#define OP_PLY_S_MX        0x37a
#define OP_TDC_MX          0x37b
#define OP_JMP_AXI_MX      0x37c
#define OP_ADC_AX_MX       0x37d
#define OP_ROR_AX_MX       0x37e
#define OP_ADC_AXL_MX      0x37f
#define OP_BRA_R_MX        0x380
#define OP_STA_DXI_MX      0x381
#define OP_BRL_RL_MX       0x382
#define OP_STA_DS_MX       0x383
#define OP_STY_D_MX        0x384
#define OP_STA_D_MX        0x385
#define OP_STX_D_MX        0x386
#define OP_STA_DL_MX       0x387
#define OP_DEY_MX          0x388
#define OP_BIT_IMM_MX      0x389
#define OP_TXA_MX          0x38a
#define OP_PHB_S_MX        0x38b
#define OP_STY_A_MX        0x38c
#define OP_STA_A_MX        0x38d
#define OP_STX_A_MX        0x38e
#define OP_STA_AL_MX       0x38f
#define OP_BCC_R_MX        0x390
#define OP_STA_DYI_MX      0x391
#define OP_STA_DI_MX       0x392
#define OP_STA_DYSI_MX     0x393
#define OP_STY_DX_MX       0x394
#define OP_STA_DX_MX       0x395
#define OP_STX_DY_MX       0x396
#define OP_STA_DYL_MX      0x397
#define OP_TYA_MX          0x398
#define OP_STA_AY_MX       0x399
#define OP_TXS_MX          0x39a
#define OP_TXY_MX          0x39b
#define OP_STZ_A_MX        0x39c
#define OP_STA_AX_MX       0x39d
#define OP_STZ_AX_MX       0x39e
#define OP_STA_AXL_MX      0x39f
#define OP_LDY_MM_MX       0x3a0
#define OP_LDA_DXI_MX      0x3a1
#define OP_LDX_IMM_MX      0x3a2
#define OP_LDA_DS_MX       0x3a3
#define OP_LDY_D_MX        0x3a4
#define OP_LDA_D_MX        0x3a5
#define OP_LDX_D_MX        0x3a6
#define OP_LDA_DL_MX       0x3a7
#define OP_TAY_MX          0x3a8
#define OP_LDA_IMM_MX      0x3a9
#define OP_TAX_MX          0x3aa
#define OP_PLB_S_MX        0x3ab
#define OP_LDY_A_MX        0x3ac
#define OP_LDA_A_MX        0x3ad
#define OP_LDX_A_MX        0x3ae
#define OP_LDA_AL_MX       0x3af
#define OP_BCS_R_MX        0x3b0
#define OP_LDA_DYI_MX      0x3b1
#define OP_LDA_DI_MX       0x3b2
#define OP_LDA_DYSI_MX     0x3b3
#define OP_LDY_DX_MX       0x3b4
#define OP_LDA_DX_MX       0x3b5
#define OP_LDX_DY_MX       0x3b6
#define OP_LDA_DYL_MX      0x3b7
#define OP_CLV_MX          0x3b8
#define OP_LDA_AY_MX       0x3b9
#define OP_TSX_MX          0x3ba
#define OP_TYX_MX          0x3bb
#define OP_LDY_AX_MX       0x3bc
#define OP_LDA_AX_MX       0x3bd
#define OP_LDX_AY_MX       0x3be
#define OP_LDA_AXL_MX      0x3bf
#define OP_CPY_IMM_MX      0x3c0
#define OP_CMP_DXI_MX      0x3c1
#define OP_REP_IMM_MX      0x3c2
#define OP_CMP_DS_MX       0x3c3
#define OP_CPY_D_MX        0x3c4
#define OP_CMP_D_MX        0x3c5
#define OP_DEC_D_MX        0x3c6
#define OP_CMP_DL_MX       0x3c7
#define OP_INY_MX          0x3c8
#define OP_CMP_IMM_MX      0x3c9
#define OP_DEX_MX          0x3ca
#define OP_WAI_MX          0x3cb
#define OP_CPY_A_MX        0x3cc
#define OP_CMP_A_MX        0x3cd
#define OP_DEC_A_MX        0x3ce
#define OP_CMP_AL_MX       0x3cf
#define OP_BNE_R_MX        0x3d0
#define OP_CMP_DYI_MX      0x3d1
#define OP_CMP_DI_MX       0x3d2
#define OP_CMP_DYSI_MX     0x3d3
#define OP_PEI_S_MX        0x3d4
#define OP_CMP_DX_MX       0x3d5
#define OP_DEC_DX_MX       0x3d6
#define OP_CMP_DYL_MX      0x3d7
#define OP_CLD_MX          0x3d8
#define OP_CMP_AY_MX       0x3d9
#define OP_PHX_S_MX        0x3da
#define OP_STP_MX          0x3db
#define OP_JML_AI_MX       0x3dc
#define OP_CMP_AX_MX       0x3dd
#define OP_DEC_AX_MX       0x3de
#define OP_CML_AXL_MX      0x3df
#define OP_CPX_IMM_MX      0x3e0
#define OP_SBC_DXI_MX      0x3e1
#define OP_SEP_IMM_MX      0x3e2
#define OP_SBC_DS_MX       0x3e3
#define OP_CPX_D_MX        0x3e4
#define OP_SBC_D_MX        0x3e5
#define OP_INC_D_MX        0x3e6
#define OP_SBC_DL_MX       0x3e7
#define OP_INX_MX          0x3e8
#define OP_SBC_IMM_MX      0x3e9
#define OP_NOP_MX          0x3ea
#define OP_XBA_MX          0x3eb
#define OP_CPX_A_MX        0x3ec
#define OP_SBC_A_MX        0x3ed
#define OP_INC_A_MX        0x3ee
#define OP_SBC_AL_MX       0x3ef
#define OP_BEQ_R_MX        0x3f0
#define OP_SBC_DYI_MX      0x3f1
#define OP_SBC_DI_MX       0x3f2
#define OP_SBC_DYSI_MX     0x3f3
#define OP_PEA_S_MX        0x3f4
#define OP_SBC_DX_MX       0x3f5
#define OP_INC_DX_MX       0x3f6
#define OP_SBC_DYL_MX      0x3f7
#define OP_SED_MX          0x3f8
#define OP_SBC_AY_MX       0x3f9
#define OP_PLX_S_MX        0x3fa
#define OP_XCE_MX          0x3fb
#define OP_JSR_AXI_MX      0x3fc
#define OP_SBC_AX_MX       0x3fd
#define OP_INC_AX_MX       0x3fe
#define OP_SBC_AXL_MX      0x3ff

#endif
